module.exports = [
  { stop_id: 1, stop_name: 'Aiguille du Mstop_idi' },
  { stop_id: 2, stop_name: 'Ancienne Poste' },
  { stop_id: 3, stop_name: 'Argentière' },
  { stop_id: 4, stop_name: 'Argentière - La Fis' },
  { stop_id: 5, stop_name: 'Auberge De Jeunesse' },
  { stop_id: 6, stop_name: 'Bellevue' },
  { stop_id: 7, stop_name: 'Cachat Le Géant' },
  { stop_id: 8, stop_name: 'Chamonix Centre' },
  { stop_id: 9, stop_name: 'Chamonix Sud' },
  { stop_id: 10, stop_name: 'Champraz' },
  { stop_id: 11, stop_name: 'F. Devouassoux' },
  { stop_id: 12, stop_name: 'Glacier Des Bossons' },
  { stop_id: 13, stop_name: 'Glacier Taconnaz' },
  { stop_id: 14, stop_name: 'Helbronner Casino' },
  { stop_id: 15, stop_name: 'Hôpital' },
  { stop_id: 16, stop_name: 'L’Arveyron' },
  { stop_id: 17, stop_name: 'La Frasse' },
  { stop_id: 18, stop_name: 'La Griaz - Le Tourchet' },
  { stop_id: 19, stop_name: 'Le Betty' },
  { stop_id: 20, stop_name: 'Le Bouchet Eglise' },
  { stop_id: 21, stop_name: 'Le Brévent' },
  { stop_id: 22, stop_name: 'Le Buet' },
  { stop_id: 23, stop_name: 'Le Couteray' },
  { stop_id: 24, stop_name: 'Le Fouilly' },
  { stop_id: 25, stop_name: 'Le Grépon' },
  { stop_id: 26, stop_name: 'Le Lavancher' },
  { stop_id: 27, stop_name: 'Le Lyret' },
  { stop_id: 28, stop_name: 'Le Mont' },
  { stop_id: 29, stop_name: 'Le Moulin' },
  { stop_id: 30, stop_name: 'Le Nant' },
  { stop_id: 31, stop_name: 'Le Plan Droit Vallorcine' },
  { stop_id: 32, stop_name: 'Le Pont' },
  { stop_id: 33, stop_name: 'Le Prarion' },
  { stop_id: 34, stop_name: 'Le Savoy' },
  { stop_id: 35, stop_name: 'Le Tour' },
  { stop_id: 36, stop_name: 'Les Biolles' },
  { stop_id: 37, stop_name: 'Les Bois' },
  { stop_id: 38, stop_name: 'Les Bossons' },
  { stop_id: 39, stop_name: 'Les Chosalets' },
  { stop_id: 40, stop_name: 'Les Combes' },
  { stop_id: 41, stop_name: 'Les Favrands' },
  { stop_id: 42, stop_name: 'Les Gaillands' },
  { stop_id: 43, stop_name: 'Les Grands Montets' },
  { stop_id: 44, stop_name: 'Les Granges' },
  { stop_id: 45, stop_name: 'Les Grassonnets' },
  { stop_id: 46, stop_name: 'Les Houches Mairie' },
  { stop_id: 47, stop_name: 'Les Iles' },
  { stop_id: 48, stop_name: 'Les Ilettes' },
  { stop_id: 49, stop_name: 'Les Montquarts' },
  { stop_id: 50, stop_name: 'Les Mouilles' },
  { stop_id: 51, stop_name: 'Les Mouilles Médiathèque' },
  { stop_id: 52, stop_name: 'Les Nants' },
  { stop_id: 53, stop_name: 'Les Pècles Moussoux' },
  { stop_id: 54, stop_name: 'Les Pélerins' },
  { stop_id: 55, stop_name: 'Les Planards' },
  { stop_id: 56, stop_name: 'Les Praz / Flégère' },
  { stop_id: 57, stop_name: 'Les Praz Poste' },
  { stop_id: 58, stop_name: 'Les Rives' },
  { stop_id: 59, stop_name: 'Les Tines' },
  { stop_id: 60, stop_name: 'Les Tissières' },
  { stop_id: 61, stop_name: 'Les Vardesses' },
  { stop_id: 62, stop_name: 'M. Croz' },
  { stop_id: 63, stop_name: 'Marie Paradis' },
  { stop_id: 64, stop_name: 'Médiathèque' },
  { stop_id: 65, stop_name: 'Montenvers Mer De Glace' },
  { stop_id: 66, stop_name: 'Montroc' },
  { stop_id: 67, stop_name: 'Mummery' },
  { stop_id: 68, stop_name: 'Pélerins Ecole' },
  { stop_id: 69, stop_name: 'Place du Poilu' },
  { stop_id: 70, stop_name: 'Place Mont Blanc' },
  { stop_id: 71, stop_name: 'Plaine Saint-Jean' },
  { stop_id: 72, stop_name: 'Saint Antoine', alias: ['Saint-Antoine'] },
  { stop_id: 73, stop_name: 'Salle Convivialité' },
  { stop_id: 74, stop_name: 'Servoz' },
  { stop_id: 75, stop_name: 'Servoz Gare' },
  { stop_id: 76, stop_name: 'Stade' },
  { stop_id: 77, stop_name: 'Taconnaz' },
  { stop_id: 78, stop_name: 'Vallot' },
  { stop_id: 79, stop_name: 'Vieux Servoz Le Lac' }
]
